### ISSUE TITLE
Failed to get Auth token using current Refresh token

### ISSUE THREAD

**Issue by higgsja** [studerw/td-ameritrade-client#11]
ref #9, #8 
I am now experiencing this issue. Created new refresh token, checked on the tdAmeritrade site with joy.

Created a clean download with git (more than once), rebuilt, no joy. Using Java 1.8.

java.lang.IllegalStateException: Failed to get auth token using current refresh token
	at com.studerw.tda.client.OauthInterceptor.intercept(OauthInterceptor.java:60)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall.execute(RealCall.kt:66)
	at com.studerw.tda.client.HttpTdaClient.getOptionChain(HttpTdaClient.java:668)
	at com.hpi.appcontrollers.TDAmeritradeFetchOptionsController.doPrices(TDAmeritradeFetchOptionsController.java:39)
	at com.hpi.appcontrollers.CmdLineController.doCommandLine(CmdLineController.java:224)
	at com.hpi.appcontrollers.AppController.startApp(AppController.java:61)
	at com.hpi.appTPCcli.TPCcliEx.main(TPCcliEx.java:19)

**Comment by studerw** [comment]
Hi @higgsja 

No need to build the app yourself. Instead, just use the 2.0.1 (or 2.0.0) in your pom or gradle build file. Don't use a 2.0.0-SNAPSHOT. It will pull the dependency from Maven Central like all other dependencies, and that should work as others had the same problem.

Let me know if that works!

**Comment by higgsja** [comment]
Ok, I am not familiar with how to do that. I cannot find the .jar on the Maven repository, which is what I use to get the config line for my gradle build file.

Where do I get that for this?

**Comment by studerw** [comment]
If you look on the readme or the main github page it’s on the first or second paragraph under ‘usage’.
