### ISSUE TITLE
Project example fetchQuote() invocation fails with UnrecognizedPropertyException "assetMainType"

### ISSUE THREAD

**Issue by brentd42** [studerw/td-ameritrade-client#33]
The simple _fetchQuote()_ example documented on the project's main page results in an **UnrecognizedPropertyException** for me …

```
Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "assetMainType" (class com.studerw.tda.model.quote.EquityQuote), not marked as ignorable (39 known properties: "52WkLow", "highPrice", "marginable", "divAmount", "assetType", "bidPrice", "mark", "exchangeName", "regularMarketLastSize", "askPrice", "lastId", "securityStatus", "lastPrice", "lowPrice", "shortable", "symbol", "askSize", "bidSize", "openPrice", "delayed", "exchange", "volatility", "digits", "netChange", "closePrice", "tradeTimeInLong", "askId", "lastSize", "bidId", "regularMarketLastPrice", "description", "totalVolume", "quoteTimeInLong", "52WkHigh", "regularMarketNetChange", "peRatio", "regularMarketTradeTimeInLong", "divDate", "divYield"])
 at [Source: java.io.BufferedInputStream@6d025197; line: 1, column: 48] (through reference chain: java.util.LinkedHashMap["MSFT"]->com.studerw.tda.model.quote.EquityQuote["assetMainType"])
	at com.studerw.tda.parse.DefaultMapper.fromJson(DefaultMapper.java:91)
	at com.studerw.tda.parse.TdaJsonParser.parseQuotes(TdaJsonParser.java:39)
	at com.studerw.tda.client.HttpTdaClient.fetchQuotes(HttpTdaClient.java:238)
	at com.studerw.tda.client.HttpTdaClient.fetchQuote(HttpTdaClient.java:246)
```

I'm new to the TD Ameritrade API, but am guessing **assetMainType** is a new JSON property and Jackson is not ignoring missing properties.  Running the the [Get Quote API](https://developer.tdameritrade.com/quotes/apis/get/marketdata/%7Bsymbol%7D/quotes) manually results in …

```
{
  "MSFT": {
    "assetType": "EQUITY",
    "assetMainType": "EQUITY",
    "cusip": "594918104",
    "symbol": "MSFT",
…
```
... which indeed shows the **assetMainType** property in the response.

I'm surprised others haven't run into this, so am guessing I'm doing something incorrectly or overlooking something.

Thanks in advance!

**Comment by studerw** [comment]
What version are you using?

On Fri, Dec 18, 2020, at 16:57, Brent Davis wrote:
> 

> The simple *fetchQuote()* example documented on the project's main page results in an *UnrecognizedPropertyException* for me …

> `Exception in thread "main" java.lang.RuntimeException: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "assetMainType" (class com.studerw.tda.model.quote.EquityQuote), not marked as ignorable (39 known properties: "52WkLow", "highPrice", "marginable", "divAmount", "assetType", "bidPrice", "mark", "exchangeName", "regularMarketLastSize", "askPrice", "lastId", "securityStatus", "lastPrice", "lowPrice", "shortable", "symbol", "askSize", "bidSize", "openPrice", "delayed", "exchange", "volatility", "digits", "netChange", "closePrice", "tradeTimeInLong", "askId", "lastSize", "bidId", "regularMarketLastPrice", "description", "totalVolume", "quoteTimeInLong", "52WkHigh", "regularMarketNetChange", "peRatio", "regularMarketTradeTimeInLong", "divDate", "divYield"])
 at [Source: java.io.BufferedInputStream@6d025197; line: 1, column: 48] (through reference chain: java.util.LinkedHashMap["MSFT"]->com.studerw.tda.model.quote.EquityQuote["assetMainType"])
	at com.studerw.tda.parse.DefaultMapper.fromJson(DefaultMapper.java:91)
	at com.studerw.tda.parse.TdaJsonParser.parseQuotes(TdaJsonParser.java:39)
	at com.studerw.tda.client.HttpTdaClient.fetchQuotes(HttpTdaClient.java:238)
	at com.studerw.tda.client.HttpTdaClient.fetchQuote(HttpTdaClient.java:246)
`
> I'm new to the TD Ameritrade API, but am guessing *assetMainType* is a new JSON property and Jackson is not ignoring missing properties. Running the the Get Quote API <https://developer.tdameritrade.com/quotes/apis/get/marketdata/%7Bsymbol%7D/quotes> manually results in …

> `{
  "MSFT": {
    "assetType": "EQUITY",
    "assetMainType": "EQUITY",
    "cusip": "594918104",
    "symbol": "MSFT",
…
`

**Comment by brentd42** [comment]
I'm using version 2.3.0.

**Comment by studerw** [comment]
Can you checkout this tiny [example project](https://github.com/studerw/tda-client-example) (updated to use 2.3.0), add your client ID and refresh token to the tda-api.properties file, and run it according to the directions in the [README](https://github.com/studerw/tda-client-example/blob/master/README.md)?

I just did it myself, and it works fine:

![image](https://user-images.githubusercontent.com/6321283/102672667-6b21ae00-415f-11eb-89f0-ba7dd973cb6e.png)

**Comment by brentd42** [comment]
Thanks for that suggestion!  The standalone example project code ran just fine.   I found the source of the above issue.  Although they didn't show in the POM dependency hierarchy, there were some older Jackson .jar files lingering in the project's classpath.

Sorry for the false alarm ... and thanks for the newbie help!
