### ISSUE TITLE
RuntimeException: Empty json body:  [200 - ] - https://api.tdameritrade.com/v1/marketdata/quotes?symbol=blahblah1

### ISSUE THREAD

**Issue by jschlade** [studerw/td-ameritrade-client#56]
Hi,

```
Using:

<dependency>
   <groupId>com.studerw.tda</groupId>
   <artifactId>td-ameritrade-client</artifactId>
   <version>2.4.1</version>
</dependency>

TdaClient client = new HttpTdaClient();
ArrayList<String> symbols = new ArrayList<>();
symbols.add("blahblah1");
List<Quote> quotes = client.fetchQuotes(symbols);

causes:

Exception in thread "main" java.lang.RuntimeException: Empty json body:  [200 - ] - https://api.tdameritrade.com/v1/marketdata/quotes?symbol=blahblah1
	at com.studerw.tda.client.HttpTdaClient.checkResponse(HttpTdaClient.java:852)
	at com.studerw.tda.client.HttpTdaClient.fetchQuotes(HttpTdaClient.java:241)
```
The code should be able to handle a bad symbol without throwing a RuntimeException.

Thanks

**Comment by studerw** [comment]
@jschlade  You really think a developer would want to get back an empty response if they pass in a symbol that TDA can't find? I could kind of see this making sense for multiple symbol requests if only one of them is bad, but definitely not in the use case you described above. Otherwise, the dev might not realize that the symbol they've passed is invalid.
